variable "availability_zone" {}
variable "ebs_volume_size" {}
variable "ec2_tags" {}
variable "cidr_block" {}
variable "ssm_role_name" {}
variable "ssm_policy_arn" {}
variable "ssm_instance_profile_name" {}
variable "vpc_tags" {}
variable "domain_name" {}
variable "ec2_ssh_key_pair_name" {}
variable "private_ssh_keyname" {}
variable "instance_type" {}
variable "ami_id" {}
variable "ebs_volume_device_name" {}
variable "ebs_tags" {}
variable "rt_name" {}
variable "rt_ipv6_cidr_block" {}
variable "rt_ipv4_cidr_block" {}
variable "subnet_tags" {}
variable "sg_tags_name" {}
variable "sg_ingress_rules" {}
variable "sg_description" {}
variable "sg_name" {}
variable "web_server_private_ip" {}
variable "aws_eip_domain" {}
variable "user_details" {}
variable "user_policy_pairs" {}
